"""
test_marpit_pipeline.py
=======================
End-to-end smoke test for the Marpit rendering pipeline.

Tests:
1. clamp_text helper
2. build_markdown — produces valid Marpit Markdown
3. render_html — calls Node.js Marpit, returns HTML with expected sections
4. Full app import (Gradio demo)
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from ux_sim_app.report.slide_generator import (
    SlideReportData, IssueSlide, StrengthSlide,
    clamp_text, build_markdown, render_html, build_report_data,
)

# ── 1. clamp_text ─────────────────────────────────────────────────────────────
assert clamp_text("Hello world", 20) == "Hello world"
assert clamp_text("A " * 50, 30).endswith("…")
assert len(clamp_text("A " * 50, 30)) <= 31  # max_chars + ellipsis char
print("✅ clamp_text OK")

# ── 2. build_markdown ─────────────────────────────────────────────────────────
data = SlideReportData(
    website_url="https://example.com",
    website_title="Example Site",
    brand_name="Example",
    logo_url="",
    overall_score=72,
    overall_summary="A decent site with room for improvement.",
    methodology="Generated by OASIS.",
    focus_areas=["Navigation", "Accessibility"],
    issues=[
        IssueSlide(
            number="02.1", category="Navigation", title="Menu Findability",
            issue_text="Users might struggle to find the main menu.",
            root_cause="The hamburger icon is too small on mobile.",
            recommendation="Increase tap target size to at least 44px.",
            screenshot_url="",
        ),
        IssueSlide(
            number="02.2", category="Accessibility", title="Missing Alt Text",
            issue_text="Screen readers cannot describe images.",
            root_cause="Images lack alt attributes.",
            recommendation="Add descriptive alt text to all images.",
            screenshot_url="",
            persona_quotes=["I couldn't understand what the image was about."],
            persona_names=["Alice"],
        ),
    ],
    strengths=[
        StrengthSlide(
            title="Clear CTA",
            brand_name="Example",
            description="The primary call-to-action button is prominent and well-placed.",
        )
    ],
)

md = build_markdown(data)
print(f"✅ build_markdown OK — {len(md)} chars, {md.count('---')} slide separators")

# Check key Marpit directives are present
assert "<!-- _class: cover -->" in md,       "Missing cover class"
assert "<!-- _class: toc -->" in md,          "Missing toc class"
assert "<!-- _class: divider -->" in md,      "Missing divider class"
assert "<!-- _class: divider-light -->" in md,"Missing divider-light class"
assert "<!-- _class: issue -->" in md,        "Missing issue class"
assert "<!-- _class: strength -->" in md,     "Missing strength class"
assert "<!-- _class: back -->" in md,         "Missing back class"
assert "Predicted User Issue" in md,          "Missing issue section label"
assert "Root Cause Analysis" in md,           "Missing root cause label"
assert "Recommendations" in md,               "Missing recommendations label"
assert "Alice" in md,                         "Missing persona name"
print("✅ Marpit directives and content OK")

# ── 3. render_html ────────────────────────────────────────────────────────────
html = render_html(data)
print(f"✅ render_html OK — {len(html)} chars")

assert "<!DOCTYPE html>" in html,        "Missing DOCTYPE"
assert "<style>" in html,                "Missing <style>"
assert "marpit" in html.lower(),         "Missing marpit container"
assert "Usability Test Report" in html,  "Missing report title"
assert "--color-bg" in html,             "Missing design token --color-bg"
assert "--font" in html,                    "Missing design token --font"
assert "section" in html,               "Missing <section> elements"
print("✅ HTML structure OK")

# ── 4. Full app import ────────────────────────────────────────────────────────
from ux_sim_app.ui.app import demo
print("✅ Full Gradio app import OK")

# ── 5. build_report_data smoke test ──────────────────────────────────────────
rd = build_report_data(
    url="https://example.com",
    scrape_data={"title": "Example Site", "logo_url": ""},
    ux_data={
        "overall_score": 65,
        "overall_summary": "Needs improvement.",
        "strengths": ["Good colour contrast"],
        "weaknesses": ["Poor navigation"],
        "dimensions": [
            {
                "name": "Navigation",
                "score": 5,
                "issues": ["Hard to find the menu"],
                "recommendations": ["Make menu more visible"],
            }
        ],
        "heuristic_checks": {
            "alt_text": {"passed": False, "detail": "3 images missing alt text", "recommendation": "Add alt text."}
        },
        "screenshots": {},
    },
    sim_results=[],
    personas=[{"name": "Alice", "age": 30}],
)
assert len(rd.issues) >= 1
md2 = build_markdown(rd)
html2 = render_html(rd)
print(f"✅ build_report_data + full pipeline OK — {len(rd.issues)} issues, {len(html2)} chars HTML")

print("\n🎉 All tests passed.")
